### ISSUE TITLE
Tip to remove the gray points around the text

### ISSUE THREAD

**Issue by Hatschipuh** [c2mx/Latex_to_jpg#1]
Very good work with this code!

I didn't find a mistake, but I played something with the code and found out how to improve the quality of the pictures.

With the current code, you always get small, weak gray points around the text in the JPG. Even if these are inconspicuous, she somehow bothered me.

To remove these points and achieve a nicer display, I made the following changes:

I changed that:
    plt.savefig(f'{path}/{jpgname}.jpg')
    im = Image.open(f'{path}/{jpgname}.jpg')
    im = trim(im)
    im.save(f'{path}/{jpgname}.jpg')

To the following:
    plt.savefig(f'{path}/{jpgname}.png')
    im = Image.open(f'{path}/{jpgname}.png')
    im = trim(im)
    im.save(f'{path}/{jpgname}.png')

This removes the small gray points around the text.

**Comment by c2mx** [comment]
Thank you for your feedback and for sharing your solution for improving the quality of the pictures!
JPG is a compression format that compresses the information in an image into small blocks to reduce file size. This compression method can introduce some distortion and noise into the image just like gray points. 
If we only change the output format from jpg to png, the `trim` function is not working when dealing with PNG files. 

To solve this problem, we can use `wand` package and ImageMagick.  I submitted a new code file (latextopng.py) to implement this.

**Comment by Hatschipuh** [comment]
Great work!
I noticed the mistake at PNG too late and tried to fix myself. Your work for PNG is much better and more efficient than my attempt!
Really great work!
